spring:
  application:
    #    应用名称
    name: ZHFS
  profiles:
    active: '@profiles.name@'
  devtools:
    restart:
      # 设置热部署
      enabled: true
      # 设置重启目录
      additional-paths: /src/main/
  thymeleaf:
    # THYMELEAF (ThymeleafAutoConfiguration)
#     开启模板缓存（默认值： true ）
#    cache: false
    # 检查模板是否存在，然后再呈现
    check-template: false
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: false
#    servlet:
      #Content-Type 的值（默认值： text/html ）
#      content-type: text/html
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
#    enabled: true
    # 模板编码
#    encoding: UTF-8
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
#    mode: HTML5
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
  servlet:
    multipart:
      #      最大请求大小（总文件大小）
      max-request-size: -1
      #      最大文件大小（单个文件大小）
#      max-file-size: 1024MB
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  banner:
    location: classpath:banner.txt
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 30m
  tomcat:
    max-http-form-post-size: 1024MB
  error:
    include-exception: true
    include-message: always
logging:
  config: classpath:logging.xml
zhfs:
  key:
    test-keys: 123456
    common-keys: 666666,888888
    admin-keys: admin123456
    file-path:
      include:
        123456: image,抖音
  config:
    captcha:
      mode: 1
      type: 1
#      difficulty: 60
      length: 4
      height: 100
      width: 200
    filter:
      request-min-interval-ms: 1000
      rate-filter-exclude-path: /favicon.ico,/static/,/error/,/getVerify/,/getFileList
      request-max-count: 20
      count-filter-exclude-path: /static/,/favicon.ico,/error/,/download/getAllFileType,/getVerify/,/download/show/,/download/split/,/getFileList
    server:
      file-prefix: 星曦向荣网
      version: 25.01.04
      max-file-name-length: 35
      max-file-path-length: 15
      home-dir: files/
