spring:
  application:
    #    应用名称
    name: file_server
  devtools:
    restart:
      # 设置热部署
      enabled: true
      # 设置重启目录
      additional-paths: /src/main/
  thymeleaf:
    # THYMELEAF (ThymeleafAutoConfiguration)
    # 开启模板缓存（默认值： true ）
    cache: false
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    servlet:
      #Content-Type 的值（默认值： text/html ）
      content-type: text/html
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: HTML5
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
  servlet:
    multipart:
      #      最大请求大小（总文件大小）
      max-request-size: 1024MB
      #      最大文件大小（单个文件大小）
#      max-file-size: 1024MB
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  banner:
    location: classpath:banner.txt
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 30m
  tomcat:
    max-http-form-post-size: 1024MB
  error:
    include-exception: true
    include-message: always
logging:
  config: classpath:logging.xml
