spring:
  devtools:
    restart:
      # 设置热部署
      enabled: true
      # 设置重启目录
      additional-paths: /src/main/
  servlet:
    multipart:
      #单个上传文件的最大值
      max-file-size: 100MB
      #最大请求文件大小（总文件大小）
      max-request-size: 100MB
server:
  tomcat:
    #设置Tomcat服务器中 HTTP POST 请求的最大表单提交大小
    max-http-form-post-size: 200MB
  servlet:
    session:
      #会话超时时间
      timeout: 10m
zhfs:
  key:
    test-keys: 123456
    common-keys: 666666,888888
    admin-keys: admin123456
    file-path:
      include:
#        123456: /image/*.png,html
  config:
    captcha:
      difficulty: 50
      length: 4
      height: 100
      width: 200
      mode: random
      type: coil
    filter:
      request-min-interval-ms: 1000
      rate-filter-exclude-path: /favicon.ico,/static/,/error/,/getVerify/,/getFileList
      request-max-count: 20
      count-filter-exclude-path: /static/,/favicon.ico,/error/,/download/getAllFileType,/getVerify/,/download/show/,/download/split/,/getFileList
    server:
      file-prefix: 星曦向荣网
      version: 25.01.06
      max-file-name-length: 35
      max-file-path-length: 15
      home-dir: files/